# Generated by Django 3.2.6 on 2022-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='bonus',
            field=models.BooleanField(default=False, verbose_name='Бонусная'),
        ),
    ]
