# Generated by Django 3.2.6 on 2021-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Причина')),
                ('outcat', models.CharField(choices=[('order', 'Заказ'), ('income', 'Приход'), ('outlay', 'Расход'), ('counter_party', 'Контрагент'), ('movement', 'Перемещение')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Касса',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('outcat', models.CharField(choices=[('order', 'Заказ'), ('income', 'Приход'), ('outlay', 'Расход'), ('counter_party', 'Контрагент'), ('movement', 'Перемещение')], max_length=255)),
                ('model_id', models.IntegerField(default=-1)),
                ('payment_type', models.CharField(choices=[('outcome', 'Расход'), ('income', 'Приход')], max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Перечисление'), ('card', 'Картой')], max_length=255)),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('outlay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.outlay', verbose_name='Причина')),
            ],
        ),
    ]
