# Generated by Django 3.2.6 on 2021-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('accepted', 'Принято')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
