# Generated by Django 3.2.6 on 2021-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('accepted', 'Принято'), ('rejected', 'Отказено')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
