# Generated by Django 3.2.6 on 2021-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='outcat',
            field=models.CharField(choices=[('order', 'Заказ'), ('retail_order', 'Розничный заказ'), ('income', 'Приход'), ('outlay', 'Расход'), ('counter_party', 'Контрагент'), ('movement', 'Перемещение')], max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='outcat',
            field=models.CharField(choices=[('order', 'Заказ'), ('retail_order', 'Розничный заказ'), ('income', 'Приход'), ('outlay', 'Расход'), ('counter_party', 'Контрагент'), ('movement', 'Перемещение')], max_length=255),
        ),
    ]
