# Generated by Django 3.2.6 on 2022-01-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20211214_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='outcat',
            field=models.CharField(choices=[('order', 'Заказ'), ('retail_order', 'Розничный заказ'), ('income', 'Приход'), ('outlay', 'Расход'), ('counter_party', 'Контрагент'), ('movement', 'Перемещение'), ('user', 'Сотрудники')], max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='outcat',
            field=models.CharField(choices=[('order', 'Заказ'), ('retail_order', 'Розничный заказ'), ('income', 'Приход'), ('outlay', 'Расход'), ('counter_party', 'Контрагент'), ('movement', 'Перемещение'), ('user', 'Сотрудники')], max_length=255),
        ),
    ]
