# Generated by Django 3.2.6 on 2021-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещение')),
                ('total', models.BigIntegerField(default=0, verbose_name='Сумма перемещение')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('completed', 'Принято'), ('rejected', 'Отменен')], default='created', max_length=100, verbose_name='Статус')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_warehouse_movements', to='warehouse.warehouse', verbose_name='Со склада')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_warehouse_movements', to='warehouse.warehouse', verbose_name='В склад')),
            ],
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('total', models.BigIntegerField(default=0, verbose_name='Сумма')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movement.movement', verbose_name='Переход')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct', verbose_name='Продукт')),
            ],
        ),
    ]
