# Generated by Django 3.2.6 on 2021-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counter_party', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('total', models.BigIntegerField(default=0, verbose_name='Сумма прихода')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('completed', 'Завершен'), ('rejected', 'Отменен')], default='created', max_length=100, verbose_name='Статус')),
                ('counter_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter_party.counterparty', verbose_name='Контрагент')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('total', models.BigIntegerField(default=0, verbose_name='Сумма')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income.income', verbose_name='Приход')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукт')),
            ],
        ),
    ]
