# Generated by Django 3.2.6 on 2021-12-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0011_auto_20211210_2020'),
        ('income', '0003_alter_incomeitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='counter_party',
        ),
        migrations.AddField(
            model_name='income',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='counter_party.provider', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
