# Generated by Django 3.2.6 on 2021-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar/', verbose_name='Фото профиля')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('lang', models.CharField(max_length=255, verbose_name='Язык')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_type', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=25, verbose_name='Тип пользователя')),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
