# Generated by Django 3.2.6 on 2021-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_region',
            field=models.CharField(choices=[('bulungur', 'Булунгур'), ('ishtikhon', 'Иштихон'), ('jomboy', 'Джомбой'), ('paishanba', 'Пайшанба'), ('koshrabot', 'Кошработ'), ('oqtosh', 'Октош'), ('nurobod', 'Нуробод'), ('laish', 'Лаиш'), ('ziadin', 'Зиадин'), ('payariq', 'Паярик'), ('juma', 'Джума'), ('gulabad', 'Гулабад'), ('tayloq', 'Тойлок'), ('urgut', 'Ургут')], default=None, max_length=255, verbose_name='Регионы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('agent', 'Агент'), ('deliver', 'Достовщик')], default='user', max_length=25, verbose_name='Тип пользователя'),
        ),
    ]
