# Generated by Django 3.2.6 on 2021-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_region',
            field=models.CharField(choices=[('bulungur', 'Булунгур'), ('ishtikhon', 'Иштихон'), ('jomboy', 'Джомбой'), ('paishanba', 'Пайшанба'), ('koshrabot', 'Кошработ'), ('oqtosh', 'Октош'), ('nurobod', 'Нуробод'), ('laish', 'Лаиш'), ('ziadin', 'Зиадин'), ('payariq', 'Паярик'), ('juma', 'Джума'), ('gulabad', 'Гулабад'), ('tayloq', 'Тойлок'), ('urgut', 'Ургут'), ('g-samaqand', 'г. Самарканд '), ('r-samaqand', 'р. Самарканд ')], max_length=255, verbose_name='Регионы'),
        ),
    ]
