# Generated by Django 3.2.6 on 2021-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211209_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('agent', 'Агент'), ('deliver', 'Достовщик')], default='agent', max_length=25, verbose_name='Тип пользователя'),
        ),
    ]
