# Generated by Django 3.2.6 on 2021-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО контрагента')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес контрагента')),
                ('content', models.CharField(max_length=255, verbose_name='Комментарии для контрагента')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс контрагента')),
            ],
        ),
    ]
