# Generated by Django 3.2.6 on 2021-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='marker',
            field=models.CharField(default=None, max_length=255, verbose_name='Координаты маркера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='region',
            field=models.CharField(choices=[('bulungur', 'Булунгур'), ('ishtikhon', 'Иштихон'), ('jomboy', 'Джомбой'), ('paishanba', 'Пайшанба'), ('koshrabot', 'Кошработ'), ('oqtosh', 'Октош'), ('nurobod', 'Нуробод'), ('laish', 'Лаиш'), ('ziadin', 'Зиадин'), ('payariq', 'Паярик'), ('juma', 'Джума'), ('gulabad', 'Гулабад'), ('tayloq', 'Тойлок'), ('urgut', 'Ургут')], default=None, max_length=255, verbose_name='Адрес контрагента'),
            preserve_default=False,
        ),
    ]
