# Generated by Django 3.2.6 on 2021-12-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0010_counterparty_counter_party_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес контрагента')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии о контрагента')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс контрагента')),
            ],
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='counter_party_type',
        ),
    ]
