# Generated by Django 3.2.6 on 2021-12-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0012_rename_name_provider_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф. И. О.')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес клиента')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии о клиенте')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс клиента')),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес поставщика'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс поставщика'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии о поставщике'),
        ),
    ]
