# Generated by Django 3.2.6 on 2021-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counter_party', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принято'), ('delivered', 'Доставлено'), ('completed', 'Завершен'), ('rejected', 'Отменен')], max_length=255, verbose_name='Статус')),
                ('total', models.BigIntegerField(default=0, verbose_name='Сумма заказа')),
                ('counter_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counter_party.counterparty', verbose_name='Контрагент')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('total', models.BigIntegerField(default=0, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Заказ')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouseproduct', verbose_name='Продукт')),
            ],
        ),
    ]
