# Generated by Django 3.2.6 on 2021-11-22 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('during_delivery', 'В процессе доставки'), ('delivered', 'Доставлено'), ('completed', 'Завершен'), ('rejected', 'Отменен')], default='created', max_length=255, verbose_name='Статус')),
                ('total_without_discount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('total', models.IntegerField(default=0, verbose_name='Сумма со скидкой')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Количество')),
                ('total_without_discount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('total', models.IntegerField(default=0, verbose_name='Сумма со скидкой')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.invoice', verbose_name='Накладная')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderitem', verbose_name='Продукт заказа')),
            ],
        ),
    ]
