# Generated by Django 3.2.6 on 2021-11-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя поставщика')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес поставщика')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон поставщика')),
                ('logo', models.ImageField(upload_to='invoice_provider_logo', verbose_name='Логотип Поставщика')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_provider',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='order.invoiceprovider', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
