# Generated by Django 3.2.6 on 2021-12-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('counter_party', '0006_alter_counterparty_region'),
        ('order', '0008_auto_20211204_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='counter_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter_party.counterparty', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct', verbose_name='Продукт'),
        ),
    ]
