# Generated by Django 3.2.6 on 2021-12-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0006_alter_counterparty_region'),
        ('order', '0009_auto_20211204_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('acceptance', 'Принятие'), ('rejected', 'Отменен')], default='created', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='counter_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='counter_party.counterparty', verbose_name='Клиент'),
        ),
    ]
