# Generated by Django 3.2.6 on 2021-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211204_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('acceptance', 'Принятие'), ('write-off', 'Списание'), ('rejected', 'Отменен')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
