# Generated by Django 3.2.6 on 2021-12-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'В обработке'), ('accepted', 'Принято'), ('delivered', 'Доставлено'), ('completed', 'Завершен'), ('rejected', 'Отменен')], max_length=255, verbose_name='Статус'),
        ),
    ]
