# Generated by Django 3.2.6 on 2021-12-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='write_off_count',
            field=models.FloatField(default=0, verbose_name='Списание кол.'),
        ),
    ]
