# Generated by Django 3.2.6 on 2021-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_returnitem_write_off_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('during_delivery', 'В процессе доставки'), ('delivered', 'Доставлено'), ('rejected', 'Отменен')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
