# Generated by Django 3.2.6 on 2021-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='returned_count',
            field=models.FloatField(default=0, verbose_name='Количество возвращаемых товаров в склад'),
        ),
    ]
