# Generated by Django 3.2.6 on 2021-12-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0013_auto_20211213_1558'),
        ('order', '0018_retailorder_retailorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_orders', to='counter_party.retailclient', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='retailorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_order_items', to='order.retailorder', verbose_name='Розничный заказ'),
        ),
    ]
