# Generated by Django 3.2.6 on 2022-01-15 11:46

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_invoice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография накладного'),
        ),
    ]
