# Generated by Django 3.2.6 on 2022-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_invoice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография накладного'),
        ),
    ]
