# Generated by Django 3.2.6 on 2022-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_invoice_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.BooleanField(default=False, verbose_name='Бонусная'),
        ),
    ]
