# Generated by Django 3.2.6 on 2022-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_for_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('simple', 'Простой'), ('bonus', 'Бонусная'), ('discount', 'Скидочная')], default='simple', max_length=255, verbose_name='Тпи элемента'),
        ),
    ]
