# Generated by Django 3.2.6 on 2022-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_invoiceitem_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_without_discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
