# Generated by Django 3.2.6 on 2022-02-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20220228_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailorder',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='retailorder',
            name='delivered_at',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
    ]
